#!/usr/bin/env bash
set -euo pipefail

PORT="${PORT:-8000}"
HOST="${HOST:-127.0.0.1}"
OPEN_PATH="${OPEN_PATH:-.}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${ROOT_DIR}"

if [[ -n "${MAPTILER_API_KEY:-}" ]]; then
  cat > "src/maptiler-config.js" <<EOF
/**
 * Generated by run-local.sh from MAPTILER_API_KEY.
 * This file is local-only and gitignored.
 */
export const MAPTILER_API_KEY = ${MAPTILER_API_KEY@Q};
EOF
  echo "Wrote src/maptiler-config.js from MAPTILER_API_KEY."
elif [[ ! -f "src/maptiler-config.js" ]]; then
  echo "Missing src/maptiler-config.js and MAPTILER_API_KEY not set."
  echo "Set MAPTILER_API_KEY or create src/maptiler-config.js first."
  exit 1
fi

if ! grep -q 'export const MAPTILER_API_KEY' "src/maptiler-config.js"; then
  if grep -q 'export const MAPCHERRY_API_TOKEN' "src/maptiler-config.js"; then
    MAPCHERRY_TOKEN="$(sed -n 's/^export const MAPCHERRY_API_TOKEN = "\(.*\)";$/\1/p' src/maptiler-config.js | head -n1)"
    if [[ -n "${MAPCHERRY_TOKEN}" ]]; then
      cat > "src/maptiler-config.js" <<EOF
/**
 * Generated by run-local.sh from existing MAPCHERRY_API_TOKEN.
 * This file is local-only and gitignored.
 */
export const MAPTILER_API_KEY = ${MAPCHERRY_TOKEN@Q};
EOF
      echo "Converted MAPCHERRY_API_TOKEN config to MAPTILER_API_KEY for local run."
    else
      echo 'export const MAPTILER_API_KEY = "";' > "src/maptiler-config.js"
      echo "Created fallback MAPTILER_API_KEY export (empty value)."
    fi
  else
    echo 'export const MAPTILER_API_KEY = "";' > "src/maptiler-config.js"
    echo "Created missing MAPTILER_API_KEY export (empty value)."
  fi
fi

echo "Running smoke checks..."
if command -v node >/dev/null 2>&1; then
  node tests/smoke-check.mjs
elif command -v node.exe >/dev/null 2>&1; then
  node.exe tests/smoke-check.mjs
else
  powershell.exe -NoProfile -Command "node tests/smoke-check.mjs"
fi

# Git Bash on Windows rewrites leading "/" arguments (e.g. "/" -> "C:/Program Files/Git/").
# Normalize OPEN_PATH to a relative path there so live-server opens the right URL.
case "${OSTYPE:-}" in
  msys*|mingw*|cygwin*)
    if [[ "${OPEN_PATH}" == /* ]]; then
      if [[ "${OPEN_PATH}" == "/" ]]; then
        OPEN_PATH="."
      else
        OPEN_PATH=".${OPEN_PATH}"
      fi
    fi
    ;;
esac

echo "Starting local server with auto reload on file changes..."
echo "URL: http://${HOST}:${PORT}${OPEN_PATH}"
npx --yes live-server . \
  --host="${HOST}" \
  --port="${PORT}" \
  --open="${OPEN_PATH}" \
  --watch="index.html,src,tests,docs" \
  --wait=100
